package com.rostan.test;

import com.rostan.model.ChatMessage;

import javax.swing.*;
import java.awt.*;
import java.net.InetAddress;
import java.net.UnknownHostException;

public class GUIClient extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private boolean connected;
    // the Client object
    private Client client;
    // the default port number
    private final int defaultPort;
    private final String defaultHost;
    
    InetAddress ipAddr;

    /**
     * @param host
     * @param port
     */
    public GUIClient(String host, int port) {
        initComponents();
        
        defaultPort = port;
        defaultHost = host;
        tfServer.setEditable(true);
        tfPort.setEditable(true);
        tfServer.setEnabled(true);
        tfPort.setEnabled(true);
        tfPort.requestFocus();
        logout.setEnabled(false);
        
        tf.setText(getIP());
        
        mulaiJam();
    }
    
    public String getIP(){
        try {
            ipAddr = InetAddress.getLocalHost();
            System.out.println(ipAddr.getHostAddress());
            
        } catch (UnknownHostException ex) {
            ex.printStackTrace();
        }
        return ipAddr.getHostAddress()+"";
    }
    
    private void mulaiJam(){
        Clock c1 = new Clock(timeLabel);
        Thread t1 = new Thread(c1);
        t1.start();
    }

    // called by the Client to append text in the TextArea 
    void append(String str) {
        ta.append(str);
        ta.setCaretPosition(ta.getText().length() - 1);
    }
    // called by the GUI is the connection failed
    // we reset our buttons, label, textfield

    void connectionFailed() {
        login.setEnabled(true);
        logout.setEnabled(false);
        whoIsIn.setEnabled(false);
        label.setText("Enter your username below");
        tf.setText(getIP());
        // reset port number and host name as a construction time
        tfPort.setText("" + defaultPort);
        tfServer.setText(defaultHost);
        // let the user change them
        tfServer.setEditable(true);
        tfPort.setEditable(true);
        tfPort.requestFocus();

        // don't react to a <CR> after the username
        //tf.removeActionListener();
        connected = false;

    }

    public Icon setIcon(String path, int size) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image newimg = img.getScaledInstance(size, size, Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputPanel = new javax.swing.JPanel();
        tfServer = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        whoIsIn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        userLabel1 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        tfPort = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textkey = new javax.swing.JTextField();
        TON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Chat");
        setResizable(false);

        InputPanel.setBackground(new Color(255, 204, 51));
        InputPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InputPanelMousePressed(evt);
            }
        });

        tfServer.setBackground(new Color(255, 204, 0));
        tfServer.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        tfServer.setForeground(new Color(255, 255, 255));
        tfServer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfServer.setText("localhost");
        tfServer.setAlignmentX(0.0F);
        tfServer.setAlignmentY(0.0F);
        tfServer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255, 204, 51)));
        tfServer.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tfServer.setOpaque(false);
        tfServer.setPreferredSize(new java.awt.Dimension(0, 25));

        userLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        userLabel.setText("SERVER ADDRESS");

        timeLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("TIME");
        timeLabel.setAlignmentY(0.0F);
        timeLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255, 204, 51)));

        whoIsIn.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        whoIsIn.setText("WHO IS ONLINE");
        whoIsIn.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255, 204, 51)));
        whoIsIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whoIsInActionPerformed(evt);
            }
        });

        ta.setColumns(20);
        ta.setForeground(new Color(255, 255, 255));
        ta.setRows(5);
        ta.setCaretColor(new Color(102, 255, 204));
        ta.setDisabledTextColor(new Color(255, 255, 255));
        ta.setEnabled(false);
        jScrollPane1.setViewportView(ta);

        userLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        userLabel1.setText("PORT");

        tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        tf.setText("anonymous");
        tf.setAlignmentX(0.0F);
        tf.setAlignmentY(0.0F);
        tf.setBorder(null);
        tf.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tf.setPreferredSize(new java.awt.Dimension(0, 25));
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });

        tfPort.setBackground(new Color(255, 204, 51));
        tfPort.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        tfPort.setForeground(new Color(255, 255, 255));
        tfPort.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPort.setText("1000");
        tfPort.setAlignmentX(0.0F);
        tfPort.setAlignmentY(0.0F);
        tfPort.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255, 204, 51)));
        tfPort.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tfPort.setOpaque(false);
        tfPort.setPreferredSize(new java.awt.Dimension(0, 25));

        login.setBackground(new Color(204, 204, 204));
        login.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label.setText("USERNAME");

        logout.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Set a Key");

        TON.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TON.setText("Turn ON Light");
        TON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TONMouseClicked(evt);
            }
        });
        TON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textkey, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(TON))
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InputPanelLayout.createSequentialGroup()
                            .addComponent(whoIsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userLabel)
                                    .addComponent(userLabel1))
                                .addGap(34, 34, 34)
                                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfServer, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(userLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLabel1))
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputPanelLayout.createSequentialGroup()
                            .addComponent(tfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whoIsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void whoIsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whoIsInActionPerformed
        client.sendMessage(new ChatMessage(ChatMessage.WHOISIN, ""));
        return;
    }//GEN-LAST:event_whoIsInActionPerformed

    private void InputPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputPanelMousePressed

    }//GEN-LAST:event_InputPanelMousePressed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // ok it is a connection request
        String username = tf.getText().trim();
        // empty username ignore it
        if (username.length() == 0) {
            return;
        }
        // empty serverAddress ignore it
        String server = tfServer.getText().trim();
        if (server.length() == 0) {
            return;
        }
        // empty or invalid port numer, ignore it
        String portNumber = tfPort.getText().trim();
        if (portNumber.length() == 0) {
            return;
        }
        int port = 0;
        try {
            port = Integer.parseInt(portNumber);
        } catch (Exception en) {
            return;   // nothing I can do if port number is not valid
        }

        // try creating a new Client with GUI
        client = new Client(server, port, username, this);
        // ClientTest if we can start the Client
        if (!client.start()) {
            return;
        }
        tf.setText("");
        label.setText("Enter your message below");
        connected = true;
        textkey.setVisible(false);
        //jlabel1.setVisible(false);

        // disable login button
        login.setEnabled(false);

        // enable the 2 buttons
        logout.setEnabled(true);
        whoIsIn.setEnabled(true);
        // disable the Server and Port JTextField
        tfServer.setEditable(false);
        tfPort.setEditable(false);

        // Action listener for when the user enter a message
        //tf.addActionListener(this);
    }//GEN-LAST:event_loginActionPerformed

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // ok it is coming from the JTextField
        if (connected) {
            // just have to send the message
            //tf.getText();
            textkey.setVisible(true);
            String texto = textkey.getText();
            int valor;
            valor = Integer.parseInt(texto);
            String var1 = this.tf.getText();
            char array[] = var1.toCharArray();
            for(int i=0; i<array.length; i++)
            {
                array[i]=(char)(array[i]-valor);
            }
            String encrypt = String.valueOf(array);
            client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, encrypt));
            /*
        
        this.jTextField1.setText (encrypt);
            */
            //client.sendMessage(new com.mbutgae.jf.chat.ChatMessage(com.mbutgae.jf.chat.ChatMessage.MESSAGE, tf.getText()));
            tf.setText("");
            return;
        }
    }//GEN-LAST:event_tfActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        System.out.println("Status Connected :" + connected);
        client.sendMessage(new ChatMessage(ChatMessage.LOGOUT, ""));
        tfServer.setEditable(true);
        tfPort.setEditable(true);
        tfServer.setEnabled(connected);
        tfPort.setEnabled(connected);
        
        tf.setText("(IP) "+getIP());
        return;
    }//GEN-LAST:event_logoutActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        tfServer.setEditable(true);
        tfPort.setEditable(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void TONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TONActionPerformed
        // TODO add your handling code here:
        client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, "The Light is turn on"));
        //client.sendMessage(new com.mbutgae.jf.chat.ChatMessage(com.mbutgae.jf.chat.ChatMessage.MESSAGE, "The Light is turn on"));
//        GUIServer foco = new GUIServer();
    }//GEN-LAST:event_TONActionPerformed

    private void TONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TONMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TONMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClient("localhost", 1000).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputPanel;
    private javax.swing.JButton TON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField textkey;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfServer;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JButton whoIsIn;
    // End of variables declaration//GEN-END:variables
}
